### PR TITLE
Patch "global jquery" assumption with explicit import from jquery module

### PR DESCRIPTION
**Pull request by waxlamp**
This will fix a bug with the `OnSet` component in Candela.

### CODE REVIEW

**Comment by waxlamp** [comment]
@jeffbaumes PTAL

**Review by jeffbaumes — APPROVED** [review]
LGTM

**Comment by waxlamp** [comment]
Thanks, @jeffbaumes. Can you either give me push access or merge this for me?

**Comment by jeffbaumes** [comment]
You should have access now.

**Pull request merged**
